spring:
  application:
    name: user-service
  data:
    jpa:
      repositories:
        enabled: true
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
app:
  jwt:
    secret: ${JWT_SECRET}
