spring:
  application:
    name: user-service
  data:
    jpa:
      repositories:
        enabled: true
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: ivan
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
